# 默认从本地加载学校边缘配置文件
localEdgeCasesFile = "./school-edge-cases.json"

# 用户配置，更详细的配置说明，请查看配置文档: https://github.com/ceajs/cea/blob/main/docs/config.md
[[users]]
# 账号用户名
username = "11"
# 账号密码
password = "11"
# 用户别名
alias = "one"
# 签到地址
addr = [""]
# 学校 ID 
school = "hqdx"

