# 默认从本地加载学校边缘配置文件
localEdgeCasesFile = "./school-edge-cases.json"

# 用户配置，更详细的配置说明，请查看配置文档: https://github.com/ceajs/cea/blob/main/docs/config.md
[[users]]
# 账号用户名
username = "1935505135"
# 账号密码
password = "qq123466"
# 用户别名
alias = "135"
# 签到地址
addr = ["119.509729", "25.92992", "福建省福州市长乐区"]
# 学校 ID 
school = "fzfu"

[[users]]
# 账号用户名
username = "21305310215"
# 账号密码
password = "hu772015"
# 用户别名
alias = "215"
# 签到地址
addr = ["119.510894", "25.931823", "福建省福州市长乐区"]
# 学校 ID 
school = "fzfu"

[[users]]
# 账号用户名
username = "2016402408439"
# 账号密码
password = "Lw.123456"
# 用户别名
alias = "439"
# 签到地址
addr = ["119.511024", "25.932176", "福建省福州市长乐区"]
# 学校 ID 
school = "fzfu"

[[users]]
# 账号用户名
username = "2153202149"
# 账号密码
password = "T18190132326"
# 用户别名
alias = "149"
# 签到地址
addr = ["119.507207","25.925487", "福建省福州市长乐区青闸线"]
# 学校 ID 
school = "fzfu"

[[users]]
# 账号用户名
username = "2035508064"
# 账号密码
password = "lianxinying071"
# 用户别名
alias = "064"
# 签到地址
addr = ["119.511024", "25.932176", "福建省福州市长乐区"]
# 学校 ID 
school = "fzfu"
