# 默认从本地加载学校边缘配置文件
localEdgeCasesFile = "./school-edge-cases.json"

# 用户配置，更详细的配置说明，请查看配置文档: https://github.com/ceajs/cea/blob/main/docs/config.md
[[users]]
# 账号用户名
username = "2152203103"
# 账号密码
password = "wqh18030299360"
# 用户别名
alias = "wqh"
# 签到地址
addr = ["119.503498", "25.932574", "福建省福州市长乐区前街东路"]
# 学校 ID 
school = "fzfu"

[[users]]
# 账号用户名
username = "21305502103"
# 账号密码
password = "qx800835"
# 用户别名
alias = "ylp"
# 签到地址
addr = ["119.503498", "25.932574", "福建省福州市长乐区前街东路"]
# 学校 ID 
school = "fzfu"

[[users]]
# 账号用户名
username = "21305502091"
# 账号密码
password = "aaa115568"
# 用户别名
alias = "xfr"
# 签到地址
addr = ["119.511452", "25.932111", "福建省福州市长乐区"]
# 学校 ID 
school = "fzfu"

[[users]]
# 账号用户名
username = "2133208140"
# 账号密码
password = "fy123123"
# 用户别名
alias = "Seven"
# 签到地址
addr = ["119.503498", "25.932574", "福建省福州市长乐区前街东路"]
# 学校 ID 
school = "fzfu"

[[users]]
# 账号用户名
username = "2035505089"
# 账号密码
password = "panziying123"
# 用户别名
alias = "pzy"
# 签到地址
addr = ["119.503498", "25.932574", "福建省福州市长乐区前街东路"]
# 学校 ID 
school = "fzfu"

[[users]]
# 账号用户名
username = "21302304044"
# 账号密码
password = "zbpdd20030926"
# 用户别名
alias = "lys"
# 签到地址
addr = ["119.508585","25.932371", "福建省福州市长乐区青闸线"]
# 学校 ID 
school = "fzfu"

[[users]]
# 账号用户名
username = "1935504145"
# 账号密码
password = "zjq123456789"
# 用户别名
alias = "145"
# 签到地址
addr = ["119.510894", "25.931823", "福建省福州市长乐区"]
# 学校 ID 
school = "fzfu"
