# 默认从本地加载学校边缘配置文件
localEdgeCasesFile = "./school-edge-cases.json"

# 用户配置，更详细的配置说明，请查看配置文档: https://github.com/ceajs/cea/blob/main/docs/config.md
[[users]]
# 账号用户名
username = "21305505046"
# 账号密码
password = "lyc15859136761"
# 用户别名
alias = "046"
# 签到地址
addr = ["119.509729", "25.92992", "福建省福州市长乐区"]
# 学校 ID 
school = "fzfu"

[[users]]
# 账号用户名
username = "21305502016"
# 账号密码
password = "wenwen2003"
# 用户别名
alias = "YLP"
# 签到地址
addr = ["119.510894", "25.931823", "福建省福州市长乐区"]
# 学校 ID 
school = "fzfu"

[[users]]
# 账号用户名
username = "1931261228"
# 账号密码
password = "lyyjy520"
# 用户别名
alias = "228"
# 签到地址
addr = ["119.507584","25.927733", "福建省福州市长乐区青闸线"]
# 学校 ID 
school = "fzfu"

[[users]]
# 账号用户名
username = "21302304053"
# 账号密码
password = "A32653045"
# 用户别名
alias = "lj"
# 签到地址
addr = ["119.503498", "25.932574", "福建省福州市长乐区前街东路"]
# 学校 ID 
school = "fzfu"

[[users]]
# 账号用户名
username = "2153601088"
# 账号密码
password = "Qwerty123"
# 用户别名
alias = "Niu7"
# 签到地址
addr = ["119.507207","25.925487", "福建省福州市长乐区青闸线"]
# 学校 ID 
school = "fzfu"

[[users]]
# 账号用户名
username = "1935502310"
# 账号密码
password = "hjj161718.."
# 用户别名
alias = "H11"
# 签到地址
addr = ["119.509729", "25.92992", "福建省福州市长乐区"]
# 学校 ID 
school = "fzfu"

[[users]]
# 账号用户名
username = "21305502052"
# 账号密码
password = "xhywh719"
# 用户别名
alias = "x717"
# 签到地址
addr = ["119.510894", "25.931823", "福建省福州市长乐区"]
# 学校 ID 
school = "fzfu"
